"""
Composition Agent
-----------------
The brain of the platform. Given a client schema and a list of insights,
it tries to satisfy each insight from the registry first.

Only calls the mart generator (LLM) for insights that have no good
registry match. Every model gets a confidence score and source tag
so the review UI can show the user what came from registry vs what
was freshly generated.

This is what makes the platform compound — the registry grows with
every run, so over time fewer and fewer models need LLM generation.
"""

from registry.model_registry import search_models, save_model, detect_domain
from registry.schema_adaptor import adapt_model, score_match
from agent.mart_generator import generate_mart


# Minimum confidence to accept a registry model without LLM fallback
CONFIDENCE_THRESHOLD = 0.65

# Minimum relevance score to even attempt adaptation
MIN_RELEVANCE = 2


def compose_marts(insights: list, schema: dict,
                  schema_context: str, joins: list) -> list:
    """
    For each insight, attempt registry retrieval first.
    Falls back to LLM generation for unmatched insights.

    Returns list of model dicts with extra metadata:
        source: "registry" | "generated" | "adapted"
        confidence: 0.0-1.0
        registry_match: name of source model if from registry
    """

    results      = []
    cache_hits   = 0
    cache_misses = 0

    print(f"\n  Composition agent processing {len(insights)} insights...")
    print(f"  Registry-first strategy (threshold: {CONFIDENCE_THRESHOLD})\n")

    for insight in insights:
        print(f"  [{insight}]")

        # Try registry first
        model, source, confidence = _retrieve_or_generate(
            insight, schema, schema_context, joins
        )

        model["source"]     = source
        model["confidence"] = confidence
        results.append(model)

        if source == "registry":
            cache_hits += 1
            print(f"    ✓ Registry hit  (confidence: {confidence})")
        elif source == "adapted":
            cache_hits += 1
            print(f"    ~ Adapted from registry (confidence: {confidence})")
        else:
            cache_misses += 1
            print(f"    + Generated by LLM")

    hit_rate = round(100 * cache_hits / max(len(insights), 1))
    print(f"\n  Registry hit rate: {hit_rate}%  "
          f"({cache_hits} hits, {cache_misses} generated)\n")

    return results


from agent.mart_generator import generate_mart, _enforce_stg_refs

def _retrieve_or_generate(insight, schema, schema_context, joins):
    candidates = search_models(schema, limit=5)
    relevant   = _filter_by_insight(insight, candidates)

    if relevant:
        best = relevant[0]
        adapted_sql, confidence = adapt_model(best["sql"], schema)

        if confidence >= CONFIDENCE_THRESHOLD:
            # Enforce stg_ refs on adapted models too
            adapted_sql = _enforce_stg_refs(adapted_sql)
            source = "registry" if confidence >= 0.9 else "adapted"
            model = {
                "name":           f"mart_{insight}",
                "layer":          "mart",
                "sql":            adapted_sql,
                "registry_match": best["name"],
            }
            return model, source, confidence

    model = generate_mart(insight, schema_context, joins)
    model["registry_match"] = None
    return model, "generated", 0.0


def _filter_by_insight(insight: str, candidates: list) -> list:
    """
    From registry search results, keep only those relevant to this insight.
    Uses keyword overlap between insight name and model name/template.
    """

    insight_words = set(insight.lower().split("_"))
    scored = []

    for c in candidates:
        model_words   = set(c["name"].lower().split("_"))
        template_words = set(c["template_type"].lower().split("_"))

        overlap = len(insight_words & (model_words | template_words))
        if overlap > 0 or c["relevance"] >= MIN_RELEVANCE:
            scored.append((overlap + c["relevance"] * 0.5, c))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [c for _, c in scored]


def save_successful_models(models: list, schema: dict):
    """
    After a successful dbt run, save all generated/adapted models
    back to the registry so future clients benefit.
    Only saves models that were LLM-generated or adapted
    (registry hits are already stored).
    """

    saved = 0
    for model in models:
        if model.get("source") in ("generated", "adapted"):
            template_type = _infer_template_type(model["sql"])
            save_model(
                name          = model["name"],
                sql           = model["sql"],
                schema        = schema,
                template_type = template_type,
                quality_score = 100.0
            )
            saved += 1

    if saved:
        print(f"  Registry: {saved} new model(s) saved for future reuse")


def _infer_template_type(sql: str) -> str:
    """Infer template type from SQL content for registry metadata."""
    sql_lower = sql.lower()

    if any(k in sql_lower for k in ["stg_invoice", "is_paid", "due_date", "tax"]):
        return "invoice_analysis"
    if any(k in sql_lower for k in ["stg_order_item", "stg_product", "quantity", "margin"]):
        return "product_analysis"
    if any(k in sql_lower for k in ["stg_customer", "signup_date", "segment", "is_active"]):
        return "customer_analysis"
    return "revenue_analysis"


def get_composition_stats(models: list) -> dict:
    """Return stats about how models were sourced in this run."""
    total     = len(models)
    registry  = sum(1 for m in models if m.get("source") == "registry")
    adapted   = sum(1 for m in models if m.get("source") == "adapted")
    generated = sum(1 for m in models if m.get("source") == "generated")
    avg_conf  = (
        sum(m.get("confidence", 0) for m in models) / total
        if total else 0
    )

    return {
        "total":          total,
        "from_registry":  registry,
        "adapted":        adapted,
        "generated":      generated,
        "hit_rate_pct":   round(100 * (registry + adapted) / max(total, 1)),
        "avg_confidence": round(avg_conf, 2),
    }
