SELECT
  TO_CHAR(TRY_TO_DATE(ORDER_DATE)) AS order_date,
  CUSTOMER_ID,
  TOTAL_AMOUNT,
  ORDER_ID,
  COALESCE(STATUS, 'UNKNOWN') AS status
FROM {{ source('raw', 'ORDER_DETAIL') }}
WHERE
  TRY_TO_DATE(ORDER_DATE) IS NOT NULL
  AND TOTAL_AMOUNT IS NOT NULL
  AND STATUS IS NOT NULL